using System;
using System.Collections.Generic;

namespace SentenceGenerator
{
	static public class Constants
	{
		public enum Vowel
    {
			a,
			e,
			i,
			o,
			u
    }
		static public Dictionary<string, (string Past, string PastParticiple)> IrregularVerbForms = new Dictionary<string, (string Past, string PastParticiple)>
		{
			["abide"] = ("abode", "abode"),
			["arise"] = ("arose", "arisen"),
			["awake"] = ("awoke", "awoken"),
			["bear"] = ("bore", "borne"),
			["beat"] = ("beat", "beaten"),
			["become"] = ("became", "become"),
			["beget"] = ("begat", "begotten"),
			["begin"] = ("began", "begun"),
			["bend"] = ("bent", "bent"),
			["bet"] = ("bet", "bet"),
			["bid"] = ("bid", "bid"),
			["bite"] = ("bit", "bitten"),
			["bleed"] = ("bled", "bled"),
			["blow"] = ("blew", "blown"),
			["break"] = ("broke", "broken"),
			["bring"] = ("brought", "brought"),
			["broadcast"] = ("broadcast", "broadcast"),
			["build"] = ("built", "built"),
			["burn"] = ("burnt", "burnt"),
			["burst"] = ("burst", "burst"),
			["buy"] = ("bought", "bought"),
			["can"] = ("could", "could"),
			["cast"] = ("cast", "cast"),
			["catch"] = ("caught", "caught"),
			["chide"] = ("chid", "chid"),
			["choose"] = ("chose", "chosen"),
			["cling"] = ("clung", "clung"),
			["clothe"] = ("clad", "clad"),
			["come"] = ("came", "come"),
			["cost"] = ("cost", "cost"),
			["creep"] = ("crept", "crept"),
			["cut"] = ("cut", "cut"),
			["deal"] = ("dealt", "dealt"),
			["dig"] = ("dug", "dug"),
			["dive"] = ("dived", "dived"),
			["do"] = ("did", "done"),
			["draw"] = ("drew", "drawn"),
			["dream"] = ("dreamt", "dreamt"),
			["drink"] = ("drank", "drunk"),
			["drive"] = ("drove", "driven"),
			["dwell"] = ("dwelt", "dwelt"),
			["eat"] = ("ate", "eaten"),
			["fall"] = ("fell", "fallen"),
			["feed"] = ("fed", "fed"),
			["feel"] = ("felt", "felt"),
			["fight"] = ("fought", "fought"),
			["find"] = ("found", "found"),
			["flee"] = ("fled", "fled"),
			["fling"] = ("flung", "flung"),
			["fly"] = ("flew", "flown"),
			["forbid"] = ("forbade", "forbidden"),
			["forecast"] = ("forecast", "forecast"),
			["foresee"] = ("foresaw", "foreseen"),
			["forget"] = ("forgot", "forgotten"),
			["forgive"] = ("forgave", "forgiven"),
			["forsake"] = ("forsook", "forsaken"),
			["freeze"] = ("froze", "frozen"),
			["get"] = ("got", "gotten"),
			["give"] = ("gave", "given"),
			["go"] = ("went", "gone"),
			["grind"] = ("ground", "ground"),
			["grow"] = ("grew", "grown"),
			["hang"] = ("hung", "hung"),
			["have"] = ("had", "had"),
			["hear"] = ("heard", "heard"),
			["hide"] = ("hid", "hidden"),
			["hit"] = ("hit", "hit"),
			["hold"] = ("held", "held"),
			["hurt"] = ("hurt", "hurt"),
			["keep"] = ("kept", "kept"),
			["kneel"] = ("knelt", "knelt"),
			["know"] = ("knew", "known"),
			["lay"] = ("laid", "laid"),
			["lead"] = ("led", "led"),
			["lean"] = ("leant", "leant"),
			["leap"] = ("leapt", "leapt"),
			["learn"] = ("learnt", "learnt"),
			["leave"] = ("left", "left"),
			["lend"] = ("lent", "lent"),
			["let"] = ("let", "let"),
			["lie"] = ("lay", "lain"),
			["light"] = ("lit", "lit"),
			["lose"] = ("lost", "lost"),
			["make"] = ("made", "made"),
			["mean"] = ("meant", "meant"),
			["meet"] = ("met", "met"),
			["mow"] = ("mowed", "mowed"),
			["offset"] = ("offset", "offset"),
			["overcome"] = ("overcame", "overcome"),
			["partake"] = ("partook", "partaken"),
			["pay"] = ("paid", "paid"),
			["plead"] = ("pled", "pled"),
			["preset"] = ("preset", "preset"),
			["prove"] = ("proved", "proven"),
			["put"] = ("put", "put"),
			["quit"] = ("quit", "quit"),
			["read"] = ("read", "read"),
			["relay"] = ("relaid", "relaid"),
			["rend"] = ("rent", "rent"),
			["rid"] = ("rid", "rid"),
			["ring"] = ("rang", "rung"),
			["rise"] = ("rose", "risen"),
			["run"] = ("ran", "run"),
			["saw"] = ("saw", "sawn"),
			["say"] = ("said", "said"),
			["see"] = ("saw", "seen"),
			["seek"] = ("sought", "sought"),
			["sell"] = ("sold", "sold"),
			["send"] = ("sent", "sent"),
			["set"] = ("set", "set"),
			["shake"] = ("shook", "shaken"),
			["shed"] = ("shed", "shed"),
			["shine"] = ("shone", "shone"),
			["shoe"] = ("shod", "shod"),
			["shoot"] = ("shot", "shot"),
			["show"] = ("showed", "shown"),
			["shut"] = ("shut", "shut"),
			["sing"] = ("sang", "sung"),
			["sink"] = ("sank", "sunk"),
			["sit"] = ("sat", "sat"),
			["slay"] = ("slew", "slain"),
			["sleep"] = ("slept", "slept"),
			["slide"] = ("slid", "slid"),
			["slit"] = ("slit", "slit"),
			["smell"] = ("smelt", "smelt"),
			["sow"] = ("sowed", "sown"),
			["speak"] = ("spoke", "spoken"),
			["speed"] = ("sped", "sped"),
			["spell"] = ("spelt", "spelt"),
			["spend"] = ("spent", "spent"),
			["spill"] = ("spilt", "spilt"),
			["spin"] = ("spun", "spun"),
			["spit"] = ("spat", "spat"),
			["split"] = ("split", "split"),
			["spoil"] = ("spoilt", "spoilt"),
			["spread"] = ("spread", "spread"),
			["spring"] = ("sprang", "sprung"),
			["stand"] = ("stood", "stood"),
			["steal"] = ("stole", "stolen"),
			["stick"] = ("stuck", "stuck"),
			["sting"] = ("stung", "stung"),
			["stink"] = ("stank", "stunk"),
			["strew"] = ("strewed", "strewn"),
			["strike"] = ("struck", "stricken"),
			["strive"] = ("strove", "striven"),
			["swear"] = ("swore", "sworn"),
			["sweat"] = ("sweat", "sweat"),
			["sweep"] = ("swept", "swept"),
			["swell"] = ("swelled", "swollen"),
			["swim"] = ("swam", "swum"),
			["swing"] = ("swung", "swung"),
			["take"] = ("took", "taken"),
			["teach"] = ("taught", "taught"),
			["tear"] = ("tore", "torn"),
			["tell"] = ("told", "told"),
			["think"] = ("thought", "thought"),
			["thrive"] = ("throve", "thriven"),
			["throw"] = ("threw", "thrown"),
			["thrust"] = ("thrust", "thrust"),
			["typeset"] = ("typeset", "typeset"),
			["undergo"] = ("underwent", "undergone"),
			["understand"] = ("understood", "understood"),
			["wake"] = ("woke", "woken"),
			["wear"] = ("wore", "worn"),
			["weep"] = ("wept", "wept"),
			["wet"] = ("wet", "wet"),
			["win"] = ("won", "won"),
			["wind"] = ("wound", "wound"),
			["withdraw"] = ("withdrew", "withdrawn"),
			["wring"] = ("wrung", "wrung"),
			["write"] = ("wrote", "written")
		};
	}
}

